# Generated by Django 5.2.17 on 2026-09-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name_user_role_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Google ID'),
        ),
    ]
